### ISSUE TITLE
User defined time for the same a/c is logged again

### ISSUE THREAD

**Issue by rikgale** [kx1t/docker-planefence#100]
![image](https://user-images.githubusercontent.com/66202012/121745062-c5db0780-cafb-11eb-92f6-5ac069538993.png)
 Please can the 300 sec time out be user defined?

Many thanks
R :)

**Comment by kx1t** [comment]
I'll take a look at this early next week. Should be relatively easy to implement.

**Comment by kx1t** [comment]
Implemented in https://github.com/kx1t/docker-planefence/commit/2662ba06c5f6810a80f988674e6448849ae6f560

**Comment by rikgale** [comment]
I think is this probably working, but kinda hard to tell without spotting an ambler like that Police Observer plane. Assume working. If I do ever find a problem I'll let you know. Thank you for implementing.
