### ISSUE TITLE
Text accents being removed from tweets

### ISSUE THREAD

**Issue by Sportsbadger** [kx1t/docker-planefence#130]
The tag Luftbrücke is being truncated to Luftbrcke - https://twitter.com/AKoeppern/status/1487207837717647365?s=20&t=Nh5jEnWm-RlQKW5Uj07DyA  and Vashe Zdorov'ye to Vashe Zdorovye - https://twitter.com/AKoeppern/status/1487207160782241795?s=20&t=Nh5jEnWm-RlQKW5Uj07DyA  The same thing happens with the discord notifications. I guess this could be down to how I have formatted my list (but not sure how). The chars are in the entries on Github, so they are not being stripped out when I publish the list. And if this turn out to be a feature/difficult to solve I can just change the Luftbrücke to Luftbrucke and the problem is kinda solved.

**Comment by kx1t** [comment]
Twitter only supports alphanumerics `[A-Za-z0-9]` in hashtags, so we are restricted to that.
