### ISSUE TITLE
Plane-alert tweets everything every time

### ISSUE THREAD

**Issue by kx1t** [kx1t/docker-planefence#18]

**Comment by Sportsbadger** [comment]
I was thinking about this - maybe you could either rate limit, only tweet once per X. Or you could have a check to say... "if tweeted about plane Y in period X, then don't tweet"

**Comment by kx1t** [comment]
It's a bug. The desired/implemented behavior is that plane-alert (not planefence!) ignores multiple occurrences of the same hex id during the same day. This works, but for some reason i received a flurry of Twitter DMs.

**Comment by kx1t** [comment]
reviewed, made minor changes, and waiting for reproduction of the bug

**Comment by kx1t** [comment]
made more changes that should fix it. 
Most of the issues were related to `read -r line < file.csv` .. `read -ra record <<< "$line"`  if $line contains unescaped special characters. Weird... the `-r` option should have read in the text "raw" - maybe it get mangles or expanded somewhere downstream
