### ISSUE TITLE
Only trigger planefence when specified aircraft are seen - Accept list

### ISSUE THREAD

**Issue by Sportsbadger** [kx1t/docker-planefence#24]
Think of it as the opposite of the ignore list. In this case planefence would not trigger/log/tweet unless the aircraft seen was on the accept list. In my use case I want to trigger/log/tweet only on helicopters over my home city. I appreciate this is similar to how plane alert works, but as I want these tweets to be public I think it is a different use case.

**Comment by kx1t** [comment]
Thinking about this some more...
I rather add an option for Plane-Alert to tweet _either_ as DM _or_ as normal tweet. That way, we don't muddy the purpose of the two sub-applications: Planefence = limited area, all aircraft; Plane-Alert = feeder-wide area, specific set of aircraft.

Would that be OK?

(hmmm I guess I already violated that separation by adding "PF_PARANGE" to enable a max range for Plane-Alert, but alas...)

**Comment by Sportsbadger** [comment]
That is a far better implementation of the idea - I love it.

**Comment by kx1t** [comment]
Tweeting vs DMing Plane-Alert messages was implemented and deployed
