### ISSUE TITLE
Add aircraft to ignore / watch list via Plane fence web interface 

### ISSUE THREAD

**Issue by Sportsbadger** [kx1t/docker-planefence#26]
Would it be possible to add 2 buttons next to each entry in the plane fence  - one to add the entry to the ignore list, and another to add the aircraft to the plane-alert watch list.

**Comment by kx1t** [comment]
I am going to decline this feature - in order to implement it, we'd also need a security / login framework to ensure bad actors can't come and ruin your setup. That would be beyond the scope of what I want to do, for the time being.
