### ISSUE TITLE
Add link to ignore list from Plane Alert page

### ISSUE THREAD

**Issue by Sportsbadger** [kx1t/docker-planefence#36]
Could a link be added to the Plane Alert ignore-list from the PA homepage.

**Comment by kx1t** [comment]
The ignore list is for Planefence, not for Plane-Alert.

And yes, I can add a link to that list.

**Comment by kx1t** [comment]
Implemented in commit https://github.com/kx1t/docker-planefence/commit/2ec689b5dd1081fb7099cff7d92529aeccc1cc43
