### ISSUE TITLE
Add option to tweet interesting plane close by

### ISSUE THREAD

**Issue by darrenrobertsuk** [kx1t/docker-planefence#39]
Tweet planes on the alert list if they come within a certain radius.  Have a separate radius for plane alert, so planefence tweets all planes within 3 miles and plane-alert tweets all interesting planes with 20 miles.

**Comment by kx1t** [comment]
Implemented and deployed to `dev` for testing as of commit 
https://github.com/kx1t/docker-planefence/commit/c0e7b9402b2decbb508d7f30e5ca5b5f32281464
