### ISSUE TITLE
Reverse Chronological Order - plane alert ??

### ISSUE THREAD

**Issue by rikgale** [kx1t/docker-planefence#56]
Heya.

On the planealert page it says that the table will list things in Reverse Chronological order (I take this to mean newest at the top) Each time I go on the plane alert page the newest is at the bottom and I have to manually resort the list. Not a problem, tis only a couple of clicks

Either my understanding of Reverse Chronological order is wrong (highly possible) or there is a bug and the table defaults to chronological order, rather than reverse.

Many thanks.

**Comment by kx1t** [comment]
You are correct -- I updated the code in `dev` to have the newest item on top of the list as default sorting
Commit https://github.com/kx1t/docker-planefence/commit/fa7f36b7d2c3dae62074cee31b2ac64551ef87b9
