### ISSUE TITLE
Add additional link to PA tweets

### ISSUE THREAD

**Issue by Sportsbadger** [kx1t/docker-planefence#61]
I'd like to include an additional link in my PA DM's - this could be to a picture or a wiki page.  Basically a link that explains why the aircraft is interesting. 
Maybe a specific header could be used in the plane-alert-db.txt file to define the field that is to be  linked. I would add these to my online list (either full URLs or already shortened) and then users could edit to add their own links.

**Comment by kx1t** [comment]
This was implemented a while ago
