### ISSUE TITLE
Cache online list to cover Github failure

### ISSUE THREAD

**Issue by Sportsbadger** [kx1t/docker-planefence#95]
When github went down 30 mins ago, PA lost the column headers, tags and links from the PA webpage. The alert list was also empty whilst github was down. Could this information be cached locally and if there is no response from where it is hosted, the cached version is used.

**Comment by kx1t** [comment]
Implemented in Commit https://github.com/kx1t/docker-planefence/commit/83f2d9a4e68b9853e4dd1f03add5e32df9e0b5b9

**Comment by Sportsbadger** [comment]
Thank you for fixing this, I doubt it will happen often (but sods law says it will one day)
